### ISSUE TITLE
Cannot delete reports in v1.0.0

### ISSUE THREAD

**Issue by prasanta-biswas** [anshooarora/extentx#106]
Delete option is not there in v1.0.0

**Comment by anshooarora** [comment]
Do you mean individually?  or via admin panel?

**Comment by prasanta-biswas** [comment]
the button is not displayed in admin panel. and feature to change admin password would be nice to have.

**Comment by anshooarora** [comment]
The ability to change the user's password is there..  after you login, in the current version, you will have to refresh.  After you see the userName at the top-right, click that, the dropdown will display this option.

**Comment by anshooarora** [comment]
3/3 today. :)
