### ISSUE TITLE
selection of reports remains when clicked next

### ISSUE THREAD

**Issue by prasanta-biswas** [anshooarora/extentx#107]
Suppose i select two report by clicking the checkbox and click next, then the selection remains same on those position but the reports are different

Page 1:
<img width="1157" alt="screen shot 2017-02-16 at 6 57 00 pm" src="https://cloud.githubusercontent.com/assets/22316119/23023007/9fcb613c-f479-11e6-863c-a6007ba371f6.png">

Page 2:
<img width="1163" alt="screen shot 2017-02-16 at 6 57 10 pm" src="https://cloud.githubusercontent.com/assets/22316119/23023024/aa762b9e-f479-11e6-802b-985362dd5b0a.png">

**Comment by anshooarora** [comment]
A related feature that does not get enabled is the delete button when selecting reports..  marked this as a bug.
