### ISSUE TITLE
Project selection dropdown is cropped

### ISSUE THREAD

**Issue by prasanta-biswas** [anshooarora/extentx#108]
If project names are slightly longer, they are cropped.

<img width="1209" alt="screen shot 2017-02-16 at 6 59 17 pm" src="https://cloud.githubusercontent.com/assets/22316119/23023106/f5a3cd4c-f479-11e6-95a4-e88bb82825da.png">

This is happening just after login and when logged out state. After login the user menu gets hidden. After refresh it comes in display and the project selection dropdown is ok.

**Comment by anshooarora** [comment]
Also mentioned this in #106, marking this as a bug.

The userName fails to appear after logging on, fixing that will also correct this.
