### ISSUE TITLE
Screenshots are not showing in ExtentX1.0.1 (ExtentReports 3.0.3)

### ISSUE THREAD

**Issue by gsaimadhu** [anshooarora/extentx#119]
Anshoo,
Do we need to set any specific configuration w.r.to ExtentX?

The screenshots are shown in ExtentReports, But not showin in ExtentX.

Sample code to reproduce the issue is attached.
[ExtentTestQA.java.txt](https://github.com/anshooarora/extentx/files/859924/ExtentTestQA.java.txt)

**ExtentX report:**
![image](https://cloud.githubusercontent.com/assets/8359360/24175472/546453b8-0ebc-11e7-83ee-efdb90cc8caa.png)

**Extent report:**
![image](https://cloud.githubusercontent.com/assets/8359360/24175490/6db62148-0ebc-11e7-82e6-3d7708e73e5b.png)

Thanks
Madhusudhan G

**Comment by anshooarora** [comment]
This is a missing feature to be added on both api and server side. Will try to release in the upcoming versions.

**Comment by gsaimadhu** [comment]
Thanks Anshoo, When can we expect the new version?

**Comment by gsaimadhu** [comment]
Anshoo, any updates on availability of fix?

**Comment by anshooarora** [comment]
This will be available starting version 3.0.4 onwards.. Will be releasing this version today.

**Comment by gsaimadhu** [comment]
Anshoo, 
Screenshots are not coming with 3.0.4. Tested with the attached ExtentTestQA.java 

Getting error while capturing screenshot:
Starting ChromeDriver 2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed) on port 6928
Only local connections are allowed.
Apr 04, 2017 4:31:39 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Apr 04, 2017 4:31:43 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
Exception in thread "main" java.lang.AssertionError: set-cookie was not returned from the server
	at com.aventstack.extentreports.mediastorage.HttpMediaManager.storeCsrfCookie(HttpMediaManager.java:62)
	at com.aventstack.extentreports.mediastorage.HttpMediaManager.init(HttpMediaManager.java:48)
	at com.aventstack.extentreports.reporter.ExtentXReporter.initMedia(ExtentXReporter.java:588)
	at com.aventstack.extentreports.reporter.ExtentXReporter.initOnScreenCaptureAdded(ExtentXReporter.java:551)
	at com.aventstack.extentreports.reporter.ExtentXReporter.onScreenCaptureAdded(ExtentXReporter.java:539)
	at com.aventstack.extentreports.Report.lambda$addScreenCapture$8(Report.java:129)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.aventstack.extentreports.Report.addScreenCapture(Report.java:127)
	at com.aventstack.extentreports.ExtentTest.addLog(ExtentTest.java:353)
	at com.aventstack.extentreports.ExtentTest.log(ExtentTest.java:311)
	at com.aventstack.extentreports.ExtentTest.info(ExtentTest.java:441)
	at com.arcot.test.adapter.ExtentTestQA.main(ExtentTestQA.java:93)

**Comment by anshooarora** [comment]
The issue is:

```
Exception in thread "main" java.lang.AssertionError: set-cookie was not returned from the server
```

I remember you reporting this issue earlier also. I couls never reproduce it.. are the scripts running on the same system as the server?

**Comment by gsaimadhu** [comment]
Anshoo,
Test Program and ExtentX server are on different machines.

**Comment by anshooarora** [comment]
Are you setting the hostname as https?

**Comment by gsaimadhu** [comment]
do you mean https in server url setting?

try {
				// start x// initialize ExtentXReporter
				ExtentXReporter extentxReporter = new ExtentXReporter("10.131.63.161", 27017);			
				// project name
				extentxReporter.config().setProjectName("Test Project");

				// report or build name
				extentxReporter.config().setReportName("Build-1229");

				// server URL
				extentxReporter.config().setServerUrl("http://10.131.63.161:27017");

				// initialize ExtentReports and attach the HtmlReporter
				extent.attachReporter(htmlReporter,extentxReporter);

			} catch (Exception e){
				System.out.println("Error while connecting to mongo");
				e.printStackTrace();
			}

**Comment by gsaimadhu** [comment]
Anshoo, do you need any other info?

**Comment by anshooarora** [comment]
You need to point this to port 1337:

```
extentxReporter.config().setServerUrl("http://10.131.63.161:1337");
```

The server URL belongs to the URL of the ExtentX server, not the database..

**Comment by gsaimadhu** [comment]
Anshoo, ExtentX server and database are on same machine.

**Comment by anshooarora** [comment]
You still need to point to the correct ports even though the IP is same.

**Comment by gsaimadhu** [comment]
I have updated the port. Now no exception. But screenshots in ExtentX server is not shown.

**Comment by gsaimadhu** [comment]
Anshoo, do you need any other info regarding this issue?

**Comment by gsaimadhu** [comment]
Anshoo, any update on the fix?
I tried with 3.0.5 version also.

**Comment by anshooarora** [comment]
I haven't been able to repro this yet.  My screenshots do get uploaded.  Would it be possible for you to use the source and debug?  [This class](https://github.com/anshooarora/extentreports-java/blob/master/src/main/java/com/aventstack/extentreports/mediastorage/HttpMediaManager.java) is responsible for the upload, you can check its behavior and share the results.

**Comment by gsaimadhu** [comment]
Do you mean with the attached test script, the issue is not reproducible for you?

**Comment by anshooarora** [comment]
I tried with your code.  Parent tests are supporting screenshots for both tests and logs.  Children are yet to implement this feature.. I will include this as part of ExtentX by next week..

**Comment by anshooarora** [comment]
Can you try with this https://github.com/anshooarora/extentx/commit/766d8c43f616caa4c1e4d62285fe2f1cf4931df8 commit?

**Comment by gsaimadhu** [comment]
Excellent Anshoo. This is working fine. Now screenshots are seen in both extentx and extent reports.

**Comment by harsh976** [comment]
I am having same problem screenshot is not getting displayed in extenx but screenshots are coming on extent report can some one please share the info on what needs to be done @gsaimadhu can u help

**Comment by harsh976** [comment]
Image location is coming as http://localhost:1337/home/harsh/frmwork_workspace/frmwk_ui_tests/frmw_ui_automation/screenshots/InvalidLogin_1.png for extentx

and for Extent Report 
image Location is coming as
file:///home/harsh/frmwork_workspace/frmwk_ui_tests/frmw_ui_automation/screenshots/InvalidLogin_1.png
