### ISSUE TITLE
not able to get reports on dashboard when running test remotely

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentx#12]
@anshooarora 

I have started the mongod and sails lift in ma linux machine( 1.1.1.1:27017) 

i have my tests running on mac OSX and extext.x("1.1.1.1",27017) when running ma tests i was expecting the dashboard to get the reports but i see empty reports.

**Comment by anshooarora** [comment]
MongoDB and NodeJS are on the same box?  If yes, then it will work without any changes.  Reports will appear each time you call `flush()`.

**Comment by saikrishna321** [comment]
@anshooarora i have the sails and mongoD running on linux machine, no i didnt see any records on mongoDB and nothing on the DashBoard at all

**Comment by anshooarora** [comment]
if MongoDB isn't getting updated, then `flush()` method isn't able to insert data.  Something may be wrong while making a connection.  Is this Red Hat?

I haven't tested on Linux but I don't see why it won't work there if the connection is successfully initiated.

**Comment by saikrishna321** [comment]
its a Ubuntu machine

**Comment by anshooarora** [comment]
My setup is also on Ubuntu, no issues..  Can you ping your box from the test machine?

**Comment by saikrishna321** [comment]
yah i can ping.. i can open the DashBoard but i cant see anything in the dashboard.. let me give it a try again tomorrow and keep u posted..

**Comment by saikrishna321** [comment]
@anshooarora works .... i'm closing

**Comment by jaymuthus** [comment]
@saikrishna321 we are facing this issue now. We are also running the MongoDB, NodeJs and sails in the same box. We have given the proper IP and port for MongoDB. But, while loading the Dashboard, we are seeing error in the sails log like the project cannot be empty. We see a project in the Project collections. Meaning the test server is able to connect to the MongoDB and insert the data. But, sails application could not connect to the MongoDB and get the data. Could you suggest some the check points to verify?
