### ISSUE TITLE
Is there any way to get report id of extentx after flushing the report?

### ISSUE THREAD

**Issue by prasanta-biswas** [anshooarora/extentx#125]

**Comment by anshooarora** [comment]
You can get the reportId using right after you attach the reporter:

```
// java
extentxReporter.getReportId();

// .net
extentxReporter.ReportId;
```

**Comment by prasanta-biswas** [comment]
Which version of extentx has this?
I am using v0.2.2-alpha and cannot get it the way u told.

**Comment by anshooarora** [comment]
Do you want the reportId in ExtentReports or ExtentX?  

ExtentReports 3.0.4+ support providing this
ExtentX - the report appears in the list
