### ISSUE TITLE
Report display as per suite files in the generated report in the sequential execution

### ISSUE THREAD

**Issue by kiransweng** [anshooarora/extentx#129]
Hi
Our solution is driver by TestNG Framework and Integrated with Extent Reporting V2.41.1. In the execution , we keep suite files in sequential execution. (for ex: suite 1 has 10 scripts , suite 2 has 20 and suite 3 has 30 scripts) . In the report , all are displaying 1 to 30 in single shot. Is there anyway that I can show separately in the report as per suite file which is as executed. i.e , If I select Suite 1 , only 10 scripts results specific to suite 1 should be displayed. If I Select 2 in the report , only 11 to 20 scripts results specific to Suite 2 should be displayed. Just like tree mode.
Please suggest me.

**Comment by gsaimadhu** [comment]
Try with Parent child relationship while creating nodes. Suite1, 2, 3 will be parents. Scripts will be respective parent childs.

**Comment by kiransweng** [comment]
Thanks for sharing this input. I didn't get this. Here is my prototype testng.xml files
master suite file will have below suite files -
suitefile1.xml
suitefile2.xml

suitefile1.xml contains the test scripts
suitefile2.xml contains the test scripts

Can you relate parent and child here as per above suites? How to specify in the xml file.

**Comment by kiransweng** [comment]
Team,
Any further update on this?

**Comment by anshooarora** [comment]
Its possible if you create a new instance of ExtentX after the suite ends, with a new `ReportName`.  Would also recommend upgrading to version 3.0.0+ of the API so you can use the latest ExtentX release.

**Comment by kiransweng** [comment]
Hi,

Thanks for update !!!

Suites are being executed sequentially during night time , how would testNG
knows that Suite is completed? Any thoughts.

Sure , will try 3.0

Kiran Edupuganti,PMP
*M.no:* 9866424362

**Comment by anshooarora** [comment]
TestNG has a @AfterSuite annotation.

**Comment by kiransweng** [comment]
Thanks !!! Got it !!!

Kiran Edupuganti,PMP
*M.no:* 9866424362
