### ISSUE TITLE
ExtentX - data deleted automagically after few days from Mongo DB

### ISSUE THREAD

**Issue by rheab54** [anshooarora/extentx#135]
Hi there

Thanks for such an awesome reporting solution. I  implemented Extenx Reports a month ago and they were working as expected. But somehow this morning I find my MongoDB  collections have no data whatsoever. 
Any ideas?

Cheers
Rhea

**Comment by anshooarora** [comment]
That shouldn't happen unless they were manually removed or some changes with the db itself..

**Comment by rheab54** [comment]
Thanks for such a quick response. I thought so too , It is a shared server between various teams and something might have accidentally caused it. But I am not sure how to find what happened? Any ideas how to figure out what has happened?

**Comment by anshooarora** [comment]
MongoDB logs are the only way to find out.
