### ISSUE TITLE
Code block in test log is too small and cannot resize

### ISSUE THREAD

**Issue by prasanta-biswas** [anshooarora/extentx#146]
The code block in extentx report is so small and cannot resize it. Please change to the same as extent reports.

**Comment by anshooarora** [comment]
Its easy to customize the css from `assets/styles/css.css`.   Please make all such customization per your project.

**Comment by prasanta-biswas** [comment]
done

**Comment by NaveenAutomate** [comment]
Hi Prasanta,

I have same prob, can you please help how did u resolve this.

If possible can you provide css please.

thanks,
Naveen.

**Comment by prasanta-biswas** [comment]
Add the following
.code-block {
    background-color: #f8f9fa;
    border: 1px solid #ebedef;
    border-radius: 4px;
    color: #222 !important;
    font-family: Consolas,monospace;
    font-size: 13px;
    margin: 0;
    padding: 7px 10px;
    white-space: pre-wrap;
}

textarea.code-block {
	min-height: 5rem;
}
