### ISSUE TITLE
Need Build and Project name field to a bit more expanded

### ISSUE THREAD

**Issue by prasanta-biswas** [anshooarora/extentx#148]
Need project field and build field in extentx dashboard to be a bit more spacious. Otherwise the texts are getting written vertically. Looks very bad.
<img width="938" alt="screen shot 2017-05-02 at 4 57 43 pm" src="https://cloud.githubusercontent.com/assets/22316119/25616112/7d869ac8-2f58-11e7-942d-95aef67080c2.png">

**Comment by anshooarora** [comment]
Its easy to customize the css from assets/styles/css.css. Please make all such customization per your project. 
Also, if your screen resolution is larger, you will not encounter such issues.  With smaller screens, you will have to make changes to the css directly.  I develop on a 1920x1200 screen and our reports are viewed on a 3440x1440 screen.  Sorry, I can't make changes to this as this may affect other users reducing usable areas of other elements.

**Comment by anshooarora** [comment]
Another possible way is to make this table along with other elements more responsive.  However, I am not having enough bandwidth to work on styling.  Feel free to commit to this effort though, I will merge.

**Comment by prasanta-biswas** [comment]
I am not good in css styling :(
