### ISSUE TITLE
Failed to load resources MaterialIcons

### ISSUE THREAD

**Issue by andisan86** [anshooarora/extentx#156]
Hi,

We managed to install ExtentX and uploaded our test result to it. However, the web interface did not seem to pick up the Google fonts properly:

![image](https://cloud.githubusercontent.com/assets/24508969/25794741/da69b062-3404-11e7-8470-426b7c9cac55.png)

We started ExtentX using this command (as per example [here](http://extentreports.com/docs/extentx/#different-host)): 

`sails lift`

Just wondering if we need to start ExtentX as prod instead? (I have not tried this because I would need to get support account to modify).

`sails lift --prod`

Kind regards

**Comment by anshooarora** [comment]
Are you using the dist from the extebtreports.com website or GitHub latest?

**Comment by andisan86** [comment]
Hi @anshooarora ,

We are using the package from http://extentreports.com/community/

**Comment by anshooarora** [comment]
Use the latest github build and try again?

**Comment by andisan86** [comment]
Hi @anshooarora 

We re-installed ExtentX using the latest build from GitHub, but the problem persists:

![image](https://cloud.githubusercontent.com/assets/24508969/25833202/111e661e-34a2-11e7-8f31-d68945c251be.png)

May I also confirm that in the latest GitHub build, the incoming port is hard-coded to 1337?

**Comment by anshooarora** [comment]
Currently, you need to only use this command:

```
sails lift
```

or 

```
node app
```

Starting in production with `--prod` may result in such issues.

**Comment by andisan86** [comment]
Hi there,

Thanks @anshooarora the issue was indeed because ExtentX was started with `--prod` option. The issue is solved now.

Kind regards
