### ISSUE TITLE
Calling extent.x() with seeds/credentialsList database name is hard-coded in ExtentX.java rather than pulling from credentialsList

### ISSUE THREAD

**Issue by mcarriga** [anshooarora/extentx#16]
Hi Anshoo,

This ExtentX concept is awesome! One minor enhancement request. in the ExentenX.java class on line 50 the database name is hard-coded "db = mongoClient.getDatabase("extent");" - Would it be possible to have the database name get pulled from the credentialsList when calling extent.x() by passing in Seeds and credentialsList. In the credentialsList we specify the MongoCrendentails with the UserName,** DATABASE NAME**, and password. It would be awesome in the this scenario of call .x() with credentialsList if we could pull the Database name from here. The reason for this is that I am using an enterprise Shared MongoDB Environment where a dedicated team manages the MongoDB and Servers and in this case I am not able to control the name of the Database which was created. Therefore my MongoDB database has a different name than "extent". I am sure other people who work for large enterprises where they do not have direct control over the MongoDB Servers will also run into this issue.

**Comment by anshooarora** [comment]
sails creates the database, Java just consumes what is already there by the server.  To point to an existing database and allow the server to connect to an existing Mongo seed, configure [connections.js](https://github.com/anshooarora/extentx/blob/master/config/connections.js).

**Comment by mcarriga** [comment]
I believe that is on the server side right? In the Java project itself under com.relevantcodes.extentreports.ExtentX class i believe the publishing to the MongoDB is being defaulted to database called extent right? I'm still wrapping my head around the different pieces so I may be way off on this.

**Comment by mcarriga** [comment]
Ok nevermind. I just tried with the changes you mentioned and it is working as expected now. Thank you!
