### ISSUE TITLE
ExtentReports install in Visual Studio 2015

### ISSUE THREAD

**Issue by m-finn** [anshooarora/extentx#163]
Hi,

I'm completely new to c# and VS but have some programming and automated background. I'm trying to learn Selenium Extent Reports and have took one of the online code examples to understand how it works. When I use NuGet to install extent reports in VS it shows it as AventStack.ExtentReports not RelevantCodes and when i paste the code in to validate it throws a number of errors on these lines, e.g:

 using AventStack.ExtentReports; // when I use RelevantCodes it says that namespace could not be found? - I can see ExtentReports in my References

 extent = new ExtentReports(reportPath, true); //ExtentReports does not contain a constructor that has 2 arguments
 extent.LoadConfig(projectPath + "extent-config.xml"); //ExtentReports does not contain a definition for LoadConfig
 test = extent.StartTest("DemoReportPass"); //ExtentReports does not contain a definition for StartTest
 test.Log(LogStatus.Pass, "Assert pass as False"); //ExtentReports does not contain a definition for Log
 extent.EndTest(test);
 extent.Close(); //ExtentReports does not contain a definition for Close

Any idea what is going on? I'm really struggling with the online help, I'm sure its something obvious and simple I'm missing.

 Any advice appreciated - cheers

**Comment by anshooarora** [comment]
Version 2 of the API has `RelevantCodes` as the parent namespace.  Version 3 uses `AventStack`.  

Version 3 docs:  extentreports.com/docs/versions/3/net/
Version 2 docs:  extentreports.com/docs/versions/2/net/

**Comment by m-finn** [comment]
d'oh thanks!
