### ISSUE TITLE
Extent X enhancement - Add filtering based on Categories

### ISSUE THREAD

**Issue by mcarriga** [anshooarora/extentx#17]
Hi Anshoo,

On the Analysis page could you add filtering based on Categories(1 or more like a drop-down selection)? In the Analysis page for a given Project it would be nice to filter on the category that way we could see results based on say 'Regression' or 'Functional' or any other Categories.- Not only would this help to see something like Regression Vs Functional but also we use the Categories to mark Tests that are in 'Design' and since Tests in the Design phase will have many errors compared to finished Regression or Functional tests it would help by showing more accurate results which exclude test runs in Design phase. Ideally the trend graphs would be updated as well to only graph results with the included Categories.

**Comment by mcarriga** [comment]
Also in the Search pane it would be nice to add search-ability based on Category as well.

**Comment by MuthuVignesh91** [comment]
Hi Anshoo,
Can you please provide this feature. It would be very helpful

**Comment by mcarriga** [comment]
Thanks Anshoo! This Extent Reports and ExtentX are amazing and just keep getting better and better
