### ISSUE TITLE
CSRF mismatch

### ISSUE THREAD

**Issue by harsh976** [anshooarora/extentx#186]
@anshooarora 
Report does not load at once and when check following is error found in console.
**ReportController.js:62 CSRF mismatch**

Please suggest what needs to be done.

**Comment by plokeshwar** [comment]
@harsh976  @anshooarora any updates on above issue.  I am too facing this issue.  Please advise.

**Comment by anshooarora** [comment]
If you are using Java, please upgrade to version 3.1.0 of the API and Klov.

**Comment by bym332211** [comment]
@harsh976 @anshooarora 
Hi,I have upgrade to ver 3.1.0. But in sometimes ,it doesn't work well.
Would u please give me some advise plz?
thanks.

**Comment by anshooarora** [comment]
Please use Klov

https://github.com/anshooarora/klov

ExtentX is no longer supported

**Comment by harsh976** [comment]
upgrade to klov 3.1.0 does not support extentX

**Comment by bym332211** [comment]
@harsh976 @anshooarora  Thks a lot. Its working now :D
