### ISSUE TITLE
How to add a link in the report Extentx

### ISSUE THREAD

**Issue by azamat163** [anshooarora/extentx#19]
Hi, Anshoo!
In the code, add the following lines:

```
journal_class_export.log(LogStatus.PASS, "HTML","<a href =" + path_screenshot_pass + "Screenshot_pass_" + getTimeStamp()  + ".png" + ">"
                    + " Screenshot see" + "</a>");
```

After executing the code,i turn  on the report extentx. After i clicked on the link and i turn on new inset where 404 error is displayed.  
Here so the link generated on this the error:
[http://localhost:1337/Users/azamat/proj_ta/EZD/Selenium_project_EZD/Screenshots_pass/Screenshot_pass_20160512_144125.png]
()
How that is fix?

**Comment by azamat163** [comment]
i fixed problem.  See link [http://sailsjs.org/documentation/anatomy/my-app/assets/images](url)

**Comment by azamat163** [comment]
i fixed problem, see http://sailsjs.org/documentation/anatomy/my-app/assets/images

**Comment by anshooarora** [comment]
This is the same as #9 and needs to be implemented to enable image display on the server.  Please follow #9 for updates.
