### ISSUE TITLE
HTML is not interpreted within test name

### ISSUE THREAD

**Issue by arunkumarkmj** [anshooarora/extentx#190]
I am using latest version of ExtentX -1.0.2 with ExtentReport 3.0.7.

I have tests names encoded in html tags to highlight (as given in attachments). With Extent HTML report, it is shown as expected but with ExtentX I see all those html tags.

This issue is similar to what is reported against #22 .
Extent HTML Report
![extent_html](https://user-images.githubusercontent.com/16937585/31984799-68307204-b980-11e7-9682-b0fcf8583b4b.jpg)

ExtentX Report
![extentx_report](https://user-images.githubusercontent.com/16937585/31984804-6ce75d58-b980-11e7-8df8-adc94077b365.jpg)

**Comment by anshooarora** [comment]
ExtentX is deprecated. Please upgrade to Klov.

https://github.com/anshooarora/klov

It is supported by version 3.1.0+ of the API (both pro and community).
