### ISSUE TITLE
Child test node is not showing description

### ISSUE THREAD

**Issue by arunkumarkmj** [anshooarora/extentx#191]
I am using latest version of ExtentX -1.0.2 with ExtentReport 3.0.7.

I added a child test node with description where i am providing TestNG dataprovider values used for the iteration. HTML Report shows as expected, but in ExtentX , I am not seeing that data. (Refer attachments)

HTML Report
![html](https://user-images.githubusercontent.com/16937585/31998305-dd6c4062-b9ac-11e7-9882-3fc7b4d74d02.JPG)

ExtentX
![extentx](https://user-images.githubusercontent.com/16937585/31998310-e4fb24e2-b9ac-11e7-9126-faed4b816389.jpg)

**Comment by anshooarora** [comment]
ExtentX is deprecated. Please upgrade to Klov.

It is supported by version 3.1.0+ of the API (both pro and community).
