### ISSUE TITLE
ExtentReorts 3.0.7 Output file not created

### ISSUE THREAD

**Issue by WhatUGit** [anshooarora/extentx#192]
ExtentReports 3.0.7 does not appear to create a html output file 

Expected Behavior

Running the attached code should create test-output folder and create a html extent file. As I understand the Extent Reports, the file should be created if it does not already exist.

Current Behavior

The folder "test-output" is created but the file is missing. The output indicates file not found Error. Output screen shot attached. If I manually create a file, then the correct results are appended to the file. But occasionally, after repeatedly running TestNG, it appears to successfully create the file.

Sample

[ExtentDemo.txt](https://github.com/anshooarora/extentx/files/1419463/ExtentDemo.txt)

## Environment Details

* Extent report Version used: 3.0.7
* Operating System and version: Windows 10 - 1703
* JDK Version:  jdk1.8.0_144

## Screenshots
![image](https://user-images.githubusercontent.com/32855693/32067303-94c405f8-ba37-11e7-8581-f0a2a2e2b85e.png)

**Comment by RaghuveerA** [comment]
Probably folder you have pointed is not created at the time of extent report generation. So it's throwing that error. Try to create the folder in the build.xml file .

**Comment by WhatUGit** [comment]
Thank you for a quick reply ( -a quick fix to be exact). I wonder if that step, file creation in extentreports, should be internally taken care of and follows naturally after TestNG  creates the test-output file?

**Comment by RaghuveerA** [comment]
I faced same issue. So the fix was quick. Always welcome bro.

**Comment by RaghuveerA** [comment]
Can you close the ticket if issue is solved.
