### ISSUE TITLE
ExtentX - Total Scenarios, Scenarios Passed, Scenarios Failed value is not updating

### ISSUE THREAD

**Issue by AravinthanRamasamy** [anshooarora/extentx#195]
Total Scenarios, Scenarios Passed, Scenarios Failed value is not updating in Reports page header, but in Report list scenarios values are updating.

 <dependency>
    <groupId>com.aventstack</groupId>
    <artifactId>extentreports</artifactId>
    <version>3.1.0</version>
</dependency>

**Comment by anshooarora** [comment]
Please upgrade to klov.  ExtentX is no longer supported.
