### ISSUE TITLE
[enhancement] provide ability to delete reports

### ISSUE THREAD

**Issue by anshooarora** [anshooarora/extentx#20]

**Comment by mirmatei** [comment]
@anshooarora can you please provide some basic configuration or the default username/password for the admin interface?

Also, i have been using ExtentReport for some time and would like to help you identify bugs in ExtentX. If needed, i could start reporting issues.

**Comment by anshooarora** [comment]
Default login credentials are:

root/password

**Comment by anshooarora** [comment]
Please feel free to report issues.  A lot of things can change as its very early in the dev cycle but would be good to fix any issues affecting existing builds.
