### ISSUE TITLE
HTML is not interpreted inside test description

### ISSUE THREAD

**Issue by mirmatei** [anshooarora/extentx#22]
Upon reviewing the test description from inside Extent X, it can be noticed that HTML is not interpreted.

For further details please see the attachment.

![2016-05-24_1328](https://cloud.githubusercontent.com/assets/19536390/15500926/9eec30f0-21b3-11e6-8c89-27e41f2fc28b.png)

**Comment by anshooarora** [comment]
Can you share the HTML string with me?  I am unable to reproduce.

**Comment by mirmatei** [comment]
The issue occurs in the test description, not test status

**Comment by anshooarora** [comment]
Ok, here it is:  [test.html](https://github.com/anshooarora/extentx/blob/master/assets/partials/test.html#L24).  Its a quick fix, I will add it as part of the next version.

**Comment by anshooarora** [comment]
@mirmatei  - this is part of the latest 0.2-alpha-dev branch:  https://github.com/anshooarora/extentx/tree/0.2-alpha
