### ISSUE TITLE
Add feature to remove reports older than X days

### ISSUE THREAD

**Issue by tvdberk** [anshooarora/extentx#30]
History older than 5-10 runs ago are usually not very interesting. It would be a good feature if you could set a configurable value to clean up the db

**Comment by shivharen** [comment]
Is it possible to change the default password? 
Multi users possible?

**Comment by anshooarora** [comment]
The server-side signup feature for multiple users is almost ready:  https://github.com/anshooarora/extentx/blob/master/api/controllers/UserController.js.  This feature is not high up in priority though.

Feature to change password isn't implemented yet.

If you like to see these features implemented, ou can open ERs for both.

**Comment by anshooarora** [comment]
As part of the latest dev-branch for 0.2-alpha, this feature is now available for admin (root/password):  This is part of dev branch: https://github.com/anshooarora/extentx/tree/0.2-alpha

![admin-panel](https://cloud.githubusercontent.com/assets/4107384/17065681/3027014a-5011-11e6-94da-81dc17b63bea.png)
