### ISSUE TITLE
Whether Extentx test report can display Step column?

### ISSUE THREAD

**Issue by mengzi007** [anshooarora/extentx#31]
Currently I'm using ExtentX server in my selenium automation project. But I found when select one individual test, on right log panel, only 3 columns "TIMESTAMP, STATUS, DETAILS" display. Just want to know whether can configure ExtentX to display the STEP column?
Thanks.

**Comment by anshooarora** [comment]
This feature is exclusively available to ExtentReports.  The server will only allow step-details. 

Also, starting version 3, this field will no longer be available in either.
