### ISSUE TITLE
Did anyone tried setup Load Balancing URL on Extentx?

### ISSUE THREAD

**Issue by shivharen** [anshooarora/extentx#37]
Setup Extentx on server and able to access it by using \\server:host.
Reported by System Admins, that they are facing issues while setup basic Load Balancing post URL on extentx. For some reason Extentx is not supporting it. 

Anshoo, 
You or anyone successfully setup Post URL for Extentx?

**Comment by anshooarora** [comment]
ExtentX uses the sailsjs framework.  You can find some information on this topic here:  http://sailsjs.org/documentation/concepts/deployment/scaling.  

Also see the sails command line interface:  http://sailsjs.org/documentation/reference/command-line-interface/sails-lift, the port option will allow you to run it on port 80.

**Comment by praveen-4705** [comment]
@shivharen Are you able to setup URL ?
