### ISSUE TITLE
ExtentX - How to point to a different Server

### ISSUE THREAD

**Issue by malavparekh** [anshooarora/extentx#38]
I have ExtentX & MongoDB up and running on Machine A (Windows Machine)

On Machine B (Mac OS X) I just want to point to my existing installation of ExtentX & MongoDB, so as to avoid installation again. 

I understand that I can point to a different Mongo DB instance by changing the configuration but I also want to avoid the installation of NodeJS and ExtentX.

Is it posible? If yes, how?

**Comment by anshooarora** [comment]
You only need to connect to MongoDB from ExtentReports. ExtentX pulls raw data from the configured Mongo instance to display reports.

```
// http://extentreports.relevantcodes.com/java/#connect-to-extentx
// from machine b

// if mongo running on port 27017
extent.x("machine-b-ip-address");

// else
extent.x("machine-b-ip-address", port);
```

**Comment by anshooarora** [comment]
correction: it should be machine-A ip:

```
extent.x("machine-A-ip-address");
```
