### ISSUE TITLE
No response when accessing localhost:1337

### ISSUE THREAD

**Issue by RakiMohan** [anshooarora/extentx#39]
Hi Anshoo,

I have configuring the extentx reports to our project. To do so I have followed the mentioned steps in the URL.
1.Installed MongoDB.
2.Installed nodejs.
3.Installed npm.
4.Started the sails server using 'sails lift' command.

Sails server is started successfully. But when I navigate to localhost:1337 I don't see any response on the page.
Can you please help whats going wrong?
![sails_issue](https://cloud.githubusercontent.com/assets/20772735/17294589/771757d8-5815-11e6-9b68-76841d104a54.PNG)

It would be very greatful if you can help me on this.

Thanks & Regards,
Rakesh.

**Comment by anshooarora** [comment]
This does not look like the extentx folder - notice the error message right before the server starts:

```
Cannot read package.json...
```

Navigate to the extents folder and run `npm install` then `sails lift`.

**Comment by RakiMohan** [comment]
Thank you Anshoo..

**Comment by RakiMohan** [comment]
I have one more doubt.. Where should I use mongodb Connection code in my program? before ExtentReports.EndTest() ? or ExtentReports.flush()?  or any other ?
