### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentx#4]
Hello,
I would like that within the dashboard we can divide the reports in a directory structure, for example in projects which are then divided into iterations, etc.
In addition they can be displayed on the left side bar direct access to categories such as by browser type.
Greetings.

**Comment by anshooarora** [comment]
There will be a feature to allow sorting or searching by categories..  Once it is released we can work on additional features such as the one you have mentioned.  

How will we be able to divide by iteration?  This can be something you or an admin can manually do on the server.

**Comment by MaxiTalenti** [comment]
My idea is once you work the main, working couple to divide projects and reports within these in iterations (eg the scrum methodology).

You got time to launch the first beta ? I'm anxious to try it.

**Comment by anshooarora** [comment]
It will be possible to assign projects to reports and filter by them - only reports belonging to the project will be visible.

**Comment by MaxiTalenti** [comment]
Excellent!! And browser you plan to do?

**Comment by anshooarora** [comment]
Browsers?  Same as ExyentReports.
