### ISSUE TITLE
Error while ending the test.

### ISSUE THREAD

**Issue by RakiMohan** [anshooarora/extentx#41]
I am getting this error in the report. Can you please tell me what might be the reason?

"RelevantCodes.ExtentReports.ExtentTestInterruptedException: Close was called before test could end safely using EndTest."
Code:
 eTest= er.StartTest("fn_Test01","Sample Test");
 eTest.Log(LogStatus.Pass,"Test is Passed.");
 er.EndTest(eTest);
 er.Flush();

![message1](https://cloud.githubusercontent.com/assets/20772735/17328627/57e95704-58dc-11e6-84c0-cf718e467805.PNG)

**Comment by anshooarora** [comment]
Please post this in the correct repo:  extentreports-csharp.
