### ISSUE TITLE
@Show History - Can it be possible to expand child nodes side by side to compare...It will be a great addition.

### ISSUE THREAD

**Issue by shivharen** [anshooarora/extentx#46]
I want to compare child test with previous run.

![image](https://cloud.githubusercontent.com/assets/10720109/17604077/236a979c-5fe2-11e6-919b-0d7e4523b584.png)

**Comment by anshooarora** [comment]
planned for the upcoming release, ExtentReports 3.0 only.

**Comment by shivharen** [comment]
Great!...Thanks

**Comment by anshooarora** [comment]
Enhancement complete.    The upcoming version 0.2.2-alpha will have this enhancement.

Note:  this version is only compatible with ExtentReports 3.0.
