### ISSUE TITLE
Timeout error when calling report.EndTest()

### ISSUE THREAD

**Issue by ardz** [anshooarora/extentx#47]
Hello,

I am having issues with a System.TimeoutException when calling the report.EndTest() method. The extentX is up and running on my remote machine and everything looks good, I can create the new report using 

`ExtentReport = new ExtentReports(reportName);
ExtentReport.AssignProject(projectName);
const string ConnectionString = "mongodb://user:password@hostname:27017/extent";
ExtentReport.X(ConnectionString);`

But as soon as 

`ExentReport.EndTest(ExtentTest);`

is called, this error is thrown in visual studio:

  Message=A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = ReadPreferenceServerSelector{ ReadPreference = { Mode = Primary, TagSets = [] } }, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/hostname:27017" }", EndPoint: "Unspecified/hostname:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server. ---> MongoDB.Driver.MongoAuthenticationException: Unable to authenticate using sasl protocol mechanism SCRAM-SHA-1. ---> MongoDB.Driver.MongoCommandException: Command saslStart failed: Authentication failed..

Is this an issue with my connection string or have I missed something fundamental with the configuration of the mongoDB?

Any pointers appreciated. I'm not sure how to tag this as a question apologies.

**Comment by anshooarora** [comment]
You can initialize extentx this way:

```
ExtentReport = new ExtentReports(reportName); 
ExtentReport.AssignProject(projectName); 
ExtentReport.X(host, port);
```
