### ISSUE TITLE
Failed tests are not showing in the graphs/top failed widgets?

### ISSUE THREAD

**Issue by ardz** [anshooarora/extentx#48]
Hi,

I'm having an issue with the dashboard metrics - failed tests are now showing up, only when you drill down into the individual reports do you see the failed tests.

Is there something wrong with my config? Any help appreciated!

**Comment by anshooarora** [comment]
What version of ExtentReports/ExtentX?

**Comment by ardz** [comment]
v0.2-alpha shows in the top right of the page

**Comment by ardz** [comment]
The extent report object in code is showing that the report status is "Error" before calling the Flush() method but the following additional info is showing on the static members when debugging in Visual Studio:

"InternalWarning = "Close was called before test could end safely using EndTest."?

If that has anything to do with it?

**Comment by ardz** [comment]
Also worth noting the donut graph IS showing red for test errors, but it shows '0 errors'?

**Comment by anshooarora** [comment]
You can remove the `close` method.  Only use `flush`.  Are you calling `endTest`?  Can you share a sample?

**Comment by ardz** [comment]
I'm calling ExtentReport.EndTest() in the [TestCleanup] method (I'm using MSTest) then calling ExtentReport.Flush() in the [ClassCleanup] method.

**Comment by ardz** [comment]
The graphs are all showing yellow when tests are failing?

**Comment by anshooarora** [comment]
Would it be possible to share a sample?  the report?  I would like to see the code.

I don't use MsTest so not sure about correct usage but the annotation look correct based on [this page](https://msdn.microsoft.com/en-us/library/ms243147(VS.80).aspx).

**Comment by anshooarora** [comment]
Also, how many icons do you see in the sidenav?  3 or 4?

**Comment by ardz** [comment]
`        [TestCleanup]
        public virtual void AfterEachTest()
		{
			ExtentReport.EndTest(ExtentTest);
		}
		
	[ClassCleanup]
        public static void TestCleanup()
        {
		ExtentReport.Flush();
	}`

**Comment by ardz** [comment]
4 there is extentx, the four little squares, the folder and the search icon

**Comment by ardz** [comment]
attached screens
![alpha](https://cloud.githubusercontent.com/assets/6310248/17630461/488b1e04-60b7-11e6-909c-d002c042631f.png)
![bravo](https://cloud.githubusercontent.com/assets/6310248/17630465/4c0df8d0-60b7-11e6-883d-8d623bbf041c.png)

**Comment by ardz** [comment]
Which version do I need to install?

**Comment by anshooarora** [comment]
Can you use Fail status instead of Error?  That may resolve it.

**Comment by ardz** [comment]
Yeah I'm using Fail status only? Not using Error.

**Comment by anshooarora** [comment]
Are you sure?  The status shows all tests in ERROR status.  

See here:  http://extentx.herokuapp.com/#/reportDetails?id=5714e127fd7d6114d4352d70

The icons for FAIL and ERROR are different.

**Comment by ardz** [comment]
Ah yes, I can see the difference in the Icons now. I am definitely using Status Fail in my code though :(

**Comment by anshooarora** [comment]
Ah,  glad it works now.
