### ISSUE TITLE
Functional or still developing?

### ISSUE THREAD

**Issue by Bud-Herz** [anshooarora/extentx#5]
Hello @anshooarora 

Spectacular project here. Our team is excited to see it's potential. Is the current code in the repo functioning? I saw somewhere in ExtentReports a mention that documentation for ExtentX was coming soon (that was 22 days ago). 

Just fishing for an update if there is any. We would love to install it to see how well it's working.

**Comment by anshooarora** [comment]
Its still in its very early stages, but the code on github is functioning.  Documentation will be available in the coming few weeks, as soon as the server is ready for beta.  ExtentReports 2.50 will have the methods to communicate with the server - I am targeting mid April for both.

**Comment by anshooarora** [comment]
Released today, http://extentreports.relevantcodes.com.
