### ISSUE TITLE
Deploying extentx on Heroku

### ISSUE THREAD

**Issue by srikanthvejendla** [anshooarora/extentx#54]
I was trying to deploy extentx server to heroku, but i keep getting this error-

`Error: Failed to connect to MongoDB.  Are you sure your configured Mongo instance is running?`

Did you make any changes to point the mongodb to heroku instance?, If so, can you point them?

Note: I added the mongolab addon on heroku

I was trying to host my extentx reports something similar to - http://extentx.herokuapp.com/

Can you please provide info how you were able to accomplish that?

Thanks a lot

**Comment by anshooarora** [comment]
Your best bet is Heroku help.  See mongolab configuration for your server, you will have to point the server to the mongolab URL.

**Comment by srikanthvejendla** [comment]
Quickly, did you make any changes to https://github.com/anshooarora/extentx/blob/master/config/connections.js file or you made changes on mongolab on Heroku?

Thanks
