### ISSUE TITLE
ExtentX showing tests repeatedly 

### ISSUE THREAD

**Issue by vandanaheda** [anshooarora/extentx#58]
First of all, thanks Anshoo for great reporting tool for selenium using c# .
Excellent!!

I have been using extent reports for a while now and recently started using extentx as reporting server . 
I got multiple test fixtures , with varied number of tests in each . 
issue is for every test the test fixture number being run  is shown as test count in extent x and report shows it that many times . 
I can better explain with example : 
All Tests from fixture 1 shows test count 1
All Tests from fixture 2 show test count 2 
and so on

Extent report shows it correctly but its only extentx shows it multiple times, even the step count is multiplied with that many times . 

I am using
Nunit3 and C#.net 

Can you please help ? 
Attached screenshots shows results from extenreport and extentx . 
![extenreports](https://cloud.githubusercontent.com/assets/18733144/18079651/05d30946-6ed1-11e6-8fe0-6206d99f2cb2.JPG)
![extentx](https://cloud.githubusercontent.com/assets/18733144/18079652/05f0c382-6ed1-11e6-85eb-18ee1d3911e7.JPG)

Thanks.

**Comment by anshooarora** [comment]
Are you creating your reports with 'ReplaceExisting=false'?  If yes, the server will keep appending new tests and skew the counts.  If you want a single report to be stored on the server, change this flag to true so a new entry is created during each run.

PS.  The BDD style of reporting is available starting 3.0-alpha of ExtentReports and 0.2.1-alpha of ExtentX.  In prior versions, ExtentReports can be configured to provide the correct counts but there is no such setting in ExtentX.  

.NET version 3 will be available once the Java version reaches beta stage, so sometime in October/November..

**Comment by vandanaheda** [comment]
Hi Anshoo , 

Thanks for your response . I haven't set replace existing to false . 
Plus extent reports shows the right count and displays right number of tests , it is Extentx which doesn't show the right count . 

Thanks 
Vandana
