### ISSUE TITLE
Updating an existing report in ExtentX.

### ISSUE THREAD

**Issue by quldude** [anshooarora/extentx#59]
Consider the following scenario:
1. Run a test suite. This creates a report entry in ExtentX.
2. Re-run just the failed tests. At this stage, is it possible to merge the results from this run to the previous report in ExtentX?

**Comment by anshooarora** [comment]
Its possible if you mark `replaceExisting=false`.  See [here](http://extentreports.relevantcodes.com/java/#basic-usage) for more info.

**Comment by quldude** [comment]
@anshooarora I tried doing it with replaceExisting=false, but i see 2 reports in extentx instead of 1. What I would like to see is that on the second run, the previous report in extentx contains the new results as well.
