### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentx#6]
With ExtentX each report will be individual to each other? When several tests before we could join in a single file, now this will not be? I ask because now whether or not in the same file, we will be able to see in the same way ExtentX.

Greetings.

**Comment by anshooarora** [comment]
Currently, each report will be independent, and ExtentX does not implement an over-write to merge multiple reports if started with `replaceExisting = false`.

Although, it is a feature that I am currently exploring and will be available in the 1st release.

**Comment by anshooarora** [comment]
This feature is incorporated c382c66.  ExtentX will display all `replaceExisting = false` runs as a single report.
