### ISSUE TITLE
Can't show uploaded screenshoots?

### ISSUE THREAD

**Issue by asvdw** [anshooarora/extentx#60]
Hello,

Using latest extentx (Augustus 18) and latest Java reporter (also Augustus 18), I'm now able to push screenshoot to extentx server.

In fact the file is copied here:
`[my extentx directory]\.tmp\public\uploads\57c84110c32522105cced14e\57c84119c32522105cced160\1.png`

**But It is NOT shown in the report.**
This screenshot is taken after a fail, the fail is shown in the test table as expected, but the next row is the next step, I can't see picture anywhere.

As this is "alpha release", is it work in progress, or maybe something wrong with my implementation ?

PS: everything is ok with HTMLReporter, using htmlReporter.config().setAutoCreateRelativePathMedia(true);

Thank you for your great work,

**Comment by vincentlabatut** [comment]
Hi,

I have the exact same problem: screenshots have been working for months with regular HTML reports, but now using ExtentX, I can't see the actual images. Is this supported yet ?

Best regards and thanks for this cool server.

**Comment by anshooarora** [comment]
This feature is supported, and introduced with ExtentReports 3.0-alpha and ExtentX 0.2.1-alpha.  

What is the path of the image in the report?  Is it the same as in the %extentx%/.tmp/public/uploads folder?

**Comment by asvdw** [comment]
Hello,
Screenshot is created in './report/2016_09_02/2016_09_02_085133-scenarios.contact-FIREFOX-fail.png' 

I even checked if file patn is correct: 
`new File(p).exists()` return `true`
then I call ` currentTest.addScreenCaptureFromPath(p);`

Using extenxXreport: file is copied to 
%extenx\.tmp\public\uploads\57c92161c325222ed871b9f8\57c92175c325222ed871ba0a

Generated HTML, as shown in extentx,  is my fail log, then nothing before next step

<table class="table logs ng-scope" ng-if="node.logs.length">
                            <thead>
                                <tr>
                                    <th>Timestamp</th>
                                    <th>Status</th>
                                    <th>Details</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="log in node.logs" class="ng-scope">
                                    <td class="ng-binding">08:51:33</td>
                                    <td class="info">
                                        <i class="fa fa-info-circle"></i>
                                    </td>
                                    <td ng-bind-html="trust(log.details)" class="ng-binding">STARTING : scenarios.COntact-fail</td>
                                </tr><tr ng-repeat="log in node.logs" class="ng-scope">
                                    <td class="ng-binding">08:51:33</td>
                                    <td class="fatal">
                                        <i class="fa fa-times-circle"></i>
                                    </td>
                                    <td ng-bind-html="trust(log.details)" class="ng-binding"><pre>java.lang.AssertionError: This test should fail and generate screensholt
	at org.testng.Assert.fail(Assert.java:94)
	at scenarios.Contact.fail(Contact.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:74)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
</pre></td>
                                </tr>
                            </tbody>
                        </table>

Using **HTML** reporter, there is a list (ul) after this table:
```
<ul class="screenshots">
<li><img data-featherlight="extReport-2016_09_01_165155.0/2016_09_01_165204-scenarios.EthiasContact-FIREFOX-fail.png" width="25%" src="extReport-2016_09_01_165155.0/2016_09_01_165204-scenarios.Contact-FIREFOX-fail.png"></li>
</ul>
```
**BUT I can't see this list in extentx.** 
Furthermore, when I load a report, there are two suspect 404 error with this adress:

http://localhost:1337/%7B%7B%20media.path%20%7D%7D

mmm... is it the missing picture ?

**Comment by vincentlabatut** [comment]
Ok, we're not running the alpha nor the latest version of extentReports, we'll upgrade our version right away. Thanks !

**Comment by vincentlabatut** [comment]
Unfortunately, we're using exclusively extentreports for .NET and there is v3 pre-release on this platform.
Any idea when this can be available ?

**Comment by anshooarora** [comment]
I have started developing for .NET, but I don't anticipate having the 1st alpha before mid-October..

**Comment by asvdw** [comment]
Hello,
Here are some more informations about this issue. It's now short from perfect... ;)

- file upload from java client to extentx DOES work but **ONLY in first-level test;** as I can see it is not possible to append media to nested test. _Could you confirm this ?_ 

- I'm not able to zoom on picture, even if full-size picture is available. I think it's just a view to update

- If you use Htmlreporter with setAutoCreateRelativePathMedia(true) AND htmlReporter is attached _before_ extentxreporter; both java client and server crash with File not found error/exception. I suppose the file to be moved by htmlreporter before be sent to extentx. One workaround is to declare first extentxreporter, then htmlreporter.

Unfortunatelay I have no more time today to look further, but maybe it can help some of you...

**Comment by anshooarora** [comment]
I am going to recheck this, but here is another thread with related information:  https://github.com/anshooarora/extentreports-java/issues/615

The 3rd issue you mentioned isn't repro on all OS.  Which OS are you using?

**Comment by asvdw** [comment]
Yes, it's the same. I'm using osx and win10 (jdk 1.8 - mongo 3.2.9 - node v0.12.0 - what else ?)

I hope to give a further try this afternoon but can't promise it...

**Comment by asvdw** [comment]
about third issue (crash with htmlreporter), os WIN 10: 
Note that it's not severe as a simple workaround works (screenshot is nested test is the most important for me...)

```
extent = new ExtentReports();        
ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter(filename);
htmlReporter.config().setAutoCreateRelativePathMedia(true);
ExtentXReporter extentxReporter = new ExtentXReporter("localhost", 27017);
extentxReporter.config().setServerUrl("http://localhost:1337");

//extent.attachReporter(extentxReporter); // WORKS        
//extent.attachReporter(extentxReporter, htmlReporter); //WORKS
 extent.attachReporter(htmlReporter, extentxReporter); //CRASH with setAutoCreateRelativePathMedia(true) but WORKS if set to false

```

Node error: (many times)
`
error: Unable to parse HTTP body- error occurred :: 'Error: Request aborted\n    at IncomingMessage.onReqAborted (C:\\Users\\zzz\\Documents\\src\\extentReport\\extentx\\dashboard\\node_modules\\skipper\\node_modules\\multiparty\\index.js:175:17)\n    at emitNone (events.js:86:13)\n    at IncomingMessage.emit (events.js:185:7)\n    at abortIncoming (_http_server.js:280:11)\n    at Socket.serverSocketCloseListener (_http_server.js:293:5)\n    at emitOne (events.js:101:20)\n    at Socket.emit (events.js:188:7)\n    at TCP._handle.close [as _onclose] (net.js:492:12)'
`

Java error:
`
java.io.UncheckedIOException: java.io.FileNotFoundException: extReport-2016_09_13_131030.0\2016_09_13_131046-EthiasContact-FIREFOX-fail.png 
`
(note the **.0** after dir name - not sure it should be there...

Furthermore, after server has crashed, results (including previous ones) are corrupted in extentx:

![capture](https://cloud.githubusercontent.com/assets/10415605/18471969/a9584732-79b4-11e6-9738-48f414e6188d.PNG)

Let be reboot my mac and I'll confirm same result in osx.

**Comment by anshooarora** [comment]
I checked in Windows 10, and wasn't able to repro.  The other user also has this issue in OSX.

**Comment by anshooarora** [comment]
fyi - the latest commit for extentx and extentreports-java allow you to see snapshots for child tests.

**Comment by asvdw** [comment]
Hello again, 

I'm afraid it doesn't seem to work... (stupid question: did you commit all files ??)

So I've updated both extentx server and java extendReporter, clean all data.
Now there is no more broken reports (as in my post 3 days ago)... but can't see child screenshot.

This is the basic test I use - it shows all three issues: 
- htmlReporter seems to change path reference  of picture, so appending it to extentreporter throws File not found exception
- can't zoom on picture in extentx dashboard
- media not shown in child nodes (most important for me ;) )

You should be able to copy/past this snipped (and add you favorite Dog or Cat or Girlfriend picture to simulate screenshot...) to reproduce it

```
package testExtent;

import com.relevantcodes.extentreports.ExtentReports;
import com.relevantcodes.extentreports.reporter.ExtentHtmlReporter;
import com.relevantcodes.extentreports.reporter.ExtentXReporter;
import org.codehaus.plexus.util.FileUtils;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.io.File;
import java.io.IOException;

public class ExtentxTest2 {
    public static final String TEST_FILEPATH = "src/test/resources/test.png";
    private ExtentReports reporter;
    String reportDir = "./report/test/";

    @BeforeClass
    public void initListener(){
        reporter = new ExtentReports();

        ExtentHtmlReporter htmlReporter = new ExtentHtmlReporter(reportDir+"test.html");
        htmlReporter.config().setAutoCreateRelativePathMedia(true);
        ExtentXReporter extentxReporter = new ExtentXReporter("localhost", 27017);
        extentxReporter.config().setServerUrl("http://localhost:1337");
        extentxReporter.config().setProjectName("Test project");
        extentxReporter.config().setReportName("Test report");

        //reporter.attachReporter(htmlReporter); // WORKS
        reporter.attachReporter(extentxReporter); // WORKS
        //reporter.attachReporter(extentxReporter, htmlReporter); //WORKS
        //reporter.attachReporter(htmlReporter, extentxReporter); //CRASH with setAutoCreateRelativePathMedia(true) but WORKS if set to false

    }



    @Test (description = "Media and node test")
    public void loadGoogle(){

        String filepath = reportDir+"/google.png";
        takeScreenshot(filepath);

        //following line to skip dependency to FileUtils.copyFile - but it doesn't fix issues
        filepath = TEST_FILEPATH;

        try {
            reporter.createTest("media test", "test description").addScreenCaptureFromPath(filepath).info( "Screenshot post");
            reporter.createTest("node test", "test description").createNode("this is a child", "node description").addScreenCaptureFromPath(filepath).info("Screenshot in child");
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    @AfterTest
    public void tear(){
        reporter.flush();
    }

    private void takeScreenshot(String filepath){
        File screenShotFile= new File(TEST_FILEPATH);

        try {
            FileUtils.copyFile(screenShotFile, new File(filepath));

        } catch (IOException e) {
            e.printStackTrace();
        }
    }


}
```

**Comment by asvdw** [comment]
as I understood,
- media are created in db and linked to node
- node object (!) in angular doesn't have media property

**Comment by anshooarora** [comment]
I was able to attach images to child nodes.  Can you check again without using this:

```
htmlReporter.config().setAutoCreateRelativePathMedia(true);
```

I did commit all the code, this was a small fix:

https://github.com/anshooarora/extentx/commit/fd6cc4cb04b94828162e11e55ce075df41991772
https://github.com/anshooarora/extentreports-java/commit/229131ba271c5a00b3842a23f347ca915a7cffc9

**Comment by anshooarora** [comment]
Can you please check with https://github.com/anshooarora/extentx/commit/dab8697223c241d4fc3d0d7cdc6829da86d88acf.  I am able to attach snapshots to nodes at 1st and 2nd levels.

**Comment by asvdw** [comment]
great job ! It works like a charm.
I've also add featherlight support but I know nearly nothing about sails so it may not be the right way...
https://github.com/asvdw/extentx/commit/5ab66ea65d2c9150ebc5574cbf4e179700d5799b

Thank you man...
