### ISSUE TITLE
How to have a login to extentx in server

### ISSUE THREAD

**Issue by aonarun** [anshooarora/extentx#66]
Hi,

Is there any option include a login page before getting into the extentx server report page.

Also once the data in MongoDB crosses 500 records Extentx server fetches data is very slow. There is not indication to know what is happening too.

Please let us know if is you have any questions.

Thanks,
Arun

**Comment by aonarun** [comment]
Hi,

Can we download the reports from extenx server?

Thanks,
Arun

**Comment by shivharen** [comment]
Having login page is a great suggestion especially in case of viewing over internet (externally)?

**Comment by sushanthkancharla** [comment]
I have added a .Limit(100) in the ReportController.js line 59
Report.find({ project: project }).sort({ startTime: 'desc' }).limit(100).exec(function(err, result)
to resolve the performance issues. default will be 100 for all projects and users need to select the project to get 100 reports per project.

**Comment by anshooarora** [comment]
In the upcoming version, there are many performance improvements and the server implements pure pagination.  You won't have to limit the number of reports this way.

The login page is currently not available in the community version, but is in the pro-version.
