### ISSUE TITLE
Question: HTML report created, but http://localhost:1337/#/ is empty

### ISSUE THREAD

**Issue by sisillV** [anshooarora/extentx#68]
Hi anshooarora,
I really like what you did and I want to try it.
I am able to create html report, but http://localhost:1337/#/ is empty.
I use win10 install all like it is in instructions for .NET and use NUnit Example.
I don't create a project because I don't understand where to do this...

Can you please give me a hint what may be the issue?

**Comment by anshooarora** [comment]
It is required to add this to your code to use ExtentX:  [Connect to ExtentX](http://extentreports.relevantcodes.com/java/#connect-to-extentx)

**Comment by sisillV** [comment]
Sorry that bother you again but I don't know where to add this code for connection to the mongodb data base.
Actually I can not find little "x" as method for "extent" - I found only big "X" but I see error when I try to use it in [TearDown] section.
I rally don't know where to put this connection to the database in the NUnit example.

Please if you can help?
I add the errors that I see:
![bigx](https://cloud.githubusercontent.com/assets/8655116/18606649/7759b8c6-7cbe-11e6-860b-08aba21552dd.jpg)
![littlex](https://cloud.githubusercontent.com/assets/8655116/18606650/7de9e954-7cbe-11e6-96ff-19a419037097.jpg)
