### ISSUE TITLE
Error with Sidenav toggle functionality

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentx#7]
When i press **expand-sidenav** a lot of times and changed to reports, search, occurred this:

![extenx1](https://cloud.githubusercontent.com/assets/7159779/14358091/ed03d7a0-fcc1-11e5-85ae-b357e3e3186b.jpg)

![extenx2](https://cloud.githubusercontent.com/assets/7159779/14358191/4860108c-fcc2-11e5-9bdf-9d9c031542b2.jpg)

**Comment by anshooarora** [comment]
Are you running this on your host?  or http://extentx.herokuapp.com?  I am unable to reproduce this..

**Comment by MaxiTalenti** [comment]
Yes, in my host.

Enviado desde mi iPhone

**Comment by anshooarora** [comment]
Can you also tell me your OS and browser/version? 

fyi - I am unable to repro on Ubuntux64 FF and FF/Chrome/IE on Windows 10.

**Comment by MaxiTalenti** [comment]
I use Windows 7 and the latest version of Chrome

Enviado desde mi iPhone

**Comment by ossa619** [comment]
It is reproducible in MacOS-X El Capitan-10.11.4 in Chrome/Safari/Firefox(all new versions) too ....
