### ISSUE TITLE
Empty Charts

### ISSUE THREAD

**Issue by sisillV** [anshooarora/extentx#71]
Hi Anshooarora,
I manage to connect with ExtendX, but I still have problem there.
I don't see any data in the charts.
And when I open the Console I see error:
SCRIPT5007: Unable to get property 'replace' of undefined or null reference
testDetailsViewer.js (7,13)

Please see the attached files.
![emptycharts](https://cloud.githubusercontent.com/assets/8655116/18668043/dfa266b0-7f3b-11e6-935e-ba419f70c55c.png)

![emptychartserror](https://cloud.githubusercontent.com/assets/8655116/18668045/e65f5602-7f3b-11e6-9d20-c898ae948732.png)

To see the data in the ExtentX I just add 2 rows to mt 

public void FixtureInit()
        {
            var tfsProp = CommonFunctions.ReadFromPropertiesFile("C:/Users/sstoykova/Documents/Visual Studio 2015/Projects/NUnitEsTax/NUnitEsTax/TFSProperties.txt");
            extent = ExtentManager.ReportInstance(tfsProp["Suffix"]);
            extent.AssignProject("TesPprojectName");
            extent.X();

        }

Can you help me with this?

**Comment by sisillV** [comment]
Hi more information from the debug:
in TestAnalysisController.js file

$scope.pass += report.passParentLength;
                $scope.fail += report.failParentLength;
                $scope.fatal += report.fatalParentLength;
                $scope.error += report.errorParentLength;
                $scope.warning += report.warningParentLength;
                $scope.skip += report.skipParentLength;
                $scope.unknown += report.unknownParentLength;

all these report.failParentLength; report.fatalParentLength; give me Nan but I see that the status property of the report object is "fail"
And when I enter "report." in the console there is no option "failParentLength" or any of other options

![debug](https://cloud.githubusercontent.com/assets/8655116/18675016/b6ee77fe-7f59-11e6-8187-f0956c7b7a97.jpg)

**Comment by anshooarora** [comment]
You are using version 2.4.x of ExtentReports, so you must use the correct version of the server:

```
Java 2.41.1, .NET 2.41.0, ExtentX 0.2-alpha
```

* ExtentX 0.2.1-alpha is only compatible with version-3 of ExtentReports.
