### ISSUE TITLE
Screenshots on error: ExtentX 0.2-alpha 

### ISSUE THREAD

**Issue by sisillV** [anshooarora/extentx#74]
Hi Anshooarora,
I download ExtentX 0.2-alpha and the charts work in chrome and FF. 
Thank you for the support!
Now I am trying to add screenshot in the report result.
In the html reports I see the screenshot but in ExtentX 0.2-alpha screenshot is missing.
Is it supported in ExtentX 0.2-alpha?
If yes what can be the problem to not see the screenshots.

Best Regards,
Stanislava

**Comment by anshooarora** [comment]
The feature is supported with ExtentX 0.2.1 and ExtentReports 3.0 only (Java only, .NET in progress).
