### ISSUE TITLE
How to change the extentx document title?

### ISSUE THREAD

**Issue by pthewizard** [anshooarora/extentx#77]

**Comment by anshooarora** [comment]
Only possible via source.

/views/layout.ejs

**Comment by pthewizard** [comment]
can you please tell me where to change in layout.ejs?

**Comment by anshooarora** [comment]
on line 4, title: [layout.ejs](https://github.com/anshooarora/extentx/blob/master/views/layout.ejs#L4)

**Comment by pthewizard** [comment]
But all I see is:
<% var theme = ''; if (typeof req.session.theme !== 'undefined') theme = req.session.theme; %> <% include partials/header.ejs %>

**Comment by pthewizard** [comment]
Got it..Thanks!
