### ISSUE TITLE
Add features

### ISSUE THREAD

**Issue by MaxiTalenti** [anshooarora/extentx#8]
Hi!

It would be good that the graph by status reports can see for run day and not test file, I would me much more, because I make a file for each test ever. It could also specifically added some graphics test.
There will be some way to erase some reports or have an administration panel behind ExtentX?

While I could not prove it, I'll try it when I can and I'll let you know if there are any errors.

A new version will come?

Thank you for your great effort!
Regards

**Comment by anshooarora** [comment]
@MaxiTalenti - the graph by status already shows the timestamp, not the file name already.  Do you mean, show graphs by file name and not timestamps?

There will be an admin panel available, initial code is already available but need to add more features and stabilize.

**Comment by MaxiTalenti** [comment]
This is what I propose, to see if you understand.
What happens to me particularly is that for every test I do is a different html file. In addition to do exactly the chart for hours and minutes is not so necessary for me, but rather a day or weeks (though this could be set in the admin panel)

![changeextentx](https://cloud.githubusercontent.com/assets/7159779/14766734/53a6ee12-09eb-11e6-8587-2d2bf04398a6.png)

**Comment by anshooarora** [comment]
@MaxiTalenti  - you can change the format of the label by the settings of the trend panel:

![data-point-setting](https://cloud.githubusercontent.com/assets/4107384/17065631/eed5e17a-5010-11e6-90ec-d3890b57fecb.png)

This is part of dev branch:  https://github.com/anshooarora/extentx/tree/0.2-alpha
