### ISSUE TITLE
ExtentX -  extentReports.EndTest exception thrown

### ISSUE THREAD

**Issue by RazvanB2** [anshooarora/extentx#81]
Hello,

   I have created a framework with specFlow, nunit and extent. I am currently trying to get it to work with ExtentX. I have everything up and running. Reports are generated locally; mongo connection is done when running a test. The only problem is that when ending the test (extentReports.EndTest(ExtentTest);) I get an exception: `1) Error : TestINGFramework.Features.SanityAPIFeature.InitAndValidateActions
TearDown : System.ArgumentNullException : Value cannot be null.
Parameter name: value
--TearDown
   at MongoDB.Bson.BsonDocument.Add(String name, BsonValue value)
   at RelevantCodes.ExtentReports.ExtentX.GetProjectId()
   at RelevantCodes.ExtentReports.ExtentX.InsertReport()
   at RelevantCodes.ExtentReports.ExtentX.RelevantCodes.ExtentReports.IReporter.
AddTest(Test test)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at RelevantCodes.ExtentReports.Model.Report.AddTest(Test Test)
   at RelevantCodes.ExtentReports.ExtentReports.EndTest(ExtentTest Test)
   at TestINGFramework.ExtentLogger.EndTest() in D:\Projects\PlatformSolution\Te
stINGFramework\ExtentLogger.cs:line 21
   at TestINGFramework.ValidateActionsSteps.endTest() in D:\Projects\PlatformSol
ution\TestINGFramework\ValidateActionsSteps.cs:line 108
   at TechTalk.SpecFlow.Bindings.BindingInvoker.InvokeBinding(IBinding binding,
IContextManager contextManager, Object[] arguments, ITestTracer testTracer, Time
Span& duration)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.FireEvents(HookType b
indingEvent)
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnScenarioEnd()
   at TestINGFramework.Features.SanityAPIFeature.ScenarioTearDown()`

I've tried everything and I simply don't understand what's the problem; ExtentTest has data in it, the connection to the db is done ( i checked the mongo logs). Any idea of what could be the problem?

This is how I'm calling it from the steps level: `        [AfterScenario]
        public void endTest()
        {
            ExtentLogger.EndTest();
        }`

This is the ExtentLogger class: `  public static class ExtentLogger {
        public static ExtentTest ExtentTest;
        static string filePath = "D:/New folder/output.html";
        public static ExtentReports extentReports;
        public static void InitTest(string featureTitle, string featureDescription) {
            extentReports = new ExtentReports(filePath);

            //extentReports.LoadConfig(@"D:\Projects\PlatformSolution\TestINGFramework\Configuration\extent-config.xml");
            extentReports.X("mongodb://127.0.0.1:27017/extentx");
            ExtentTest = extentReports.StartTest(featureTitle, featureDescription);
        }

        public static void EndTest() {
            extentReports.EndTest(ExtentTest);
            extentReports.Flush();
        }
    }`

I'd really appreciate any advice.

Thank you,
    Razvan

**Comment by RazvanB2** [comment]
It looks like this is related to #13 just that I'm using specflow instead of testng

**Comment by sushanthkancharla** [comment]
If it's not resolved for you, try using AssignProject("some project name")
The exception looks like it's coming from ProjectId being null

**Comment by anshooarora** [comment]
can you do:

```
extentReports.X("localhost", 27017);
```

You need to point to your mongodb instance not the server itself..

**Comment by RazvanB2** [comment]
The problem was the AssignProject thingie.  Thank you.
