### ISSUE TITLE
Expanding the left panel distorts the category view

### ISSUE THREAD

**Issue by pthewizard** [anshooarora/extentx#83]
<img width="965" alt="screen shot 2016-10-18 at 10 02 21 pm" src="https://cloud.githubusercontent.com/assets/22316119/19487385/31f924bc-9580-11e6-8253-8b1b336a8a10.png">

**Comment by anshooarora** [comment]
In the upcoming version 1.0.0, the sidenav is fixed - it will not be possible to expand/collapse.  The default will be collapsed to give more space to the metrics.  

This will not be marked as an ER/bug as the current version has been deprecated and the new enhanced one will be available very soon.
