### ISSUE TITLE
Does ExtentX support old report comparisons?

### ISSUE THREAD

**Issue by naveenmails** [anshooarora/extentx#86]
We run our regression every week. With ExtentX would it be a possibility to have an executive dashboard that shows the execution percentages for current week and previous weeks ? That would help the managers know how consistent the application is.

**Comment by anshooarora** [comment]
The trend chart at the very top shows this already, no?

**Comment by naveenmails** [comment]
I just checked them.  That's exactly what we were looking for. Thank you.
