### ISSUE TITLE
Old reports are not opening properly in new version of Extent x 2.2 alpha

### ISSUE THREAD

**Issue by saorabh** [anshooarora/extentx#87]
Extentx: Old reports are not opening properly in new version of Extent x 2.2 alpha, i guess we would need to migrate old data, So how to migrate data ?

**Comment by anshooarora** [comment]
It will not be possible to use old data as several fields have changed, removed, and new fields have been added.  The server is still in alpha until 0.22 so such breaking changes can be anticipated.

Version 1.0.0 (now available) will have a very different schema so your existing data will not work, but the good news is moving forward such changes will not be required when upgrading your ExtentReports.
