### ISSUE TITLE
How to add screenshot for each steps

### ISSUE THREAD

**Issue by Vishnu1067** [anshooarora/extentx#89]
Hi, In version 2, we can add screenshot for each step. How can we add in v3?

V2 script : `ExtentTestManager.getTest().log(LogStatus.INFO, ExtentTestManager.getTest().addScreenCapture(capturedScreen));`

![get](https://cloud.githubusercontent.com/assets/13374564/20460308/7b7d7a0c-af11-11e6-8df4-1bfa3dd5add5.png)

**Comment by anshooarora** [comment]
Please use [the relevant repo](https://github.com/anshooarora/extentreports-java) to post such queries.  This is the ExtentX repo.

Starting version 3.0.1, to add snapshots to logs, see [here](http://extentreports.com/docs/versions/3/java/#insert-screenshots).
