### ISSUE TITLE
[ER] [Snapshots] How to link images to the report which is placed locally

### ISSUE THREAD

**Issue by saikrishna321** [anshooarora/extentx#9]

**Comment by anshooarora** [comment]
@saikrishna321 - how should we approach this?  Use Java to move image within network or upload the image using a server route?

**Comment by saikrishna321** [comment]
@anshooarora i feel we should just move the images within the network

**Comment by email2vimalraj** [comment]
If it is a png file, can we take the base64 string of the image file and add it to the database?

**Comment by anshooarora** [comment]
Vimal - we can, and most of the users are doing this today.  An issue with this approach is:  base64 strings take up a lot of space causing considerable performance degradation.  A user whose reports were sized to approx 1GB each and 100s of reports in the database would result in a bad user experience.  In the upcoming version, I am trying to find a way to alleviate this issue by:

Automatically creating relative paths for the users to link images with the static HTML file created by ExtentReports
Allow the images to move between network or uploaded to the server (preferred) - ExtentX

Current sources are in my private repo but I will soon move it to 3.0.0-dev branch.

**Comment by email2vimalraj** [comment]
Hi Anshoo,

Makes sense to me. How do you want to approach? Shall we deprecate the base64 feature?

Thanks
Vimalraj

**Comment by anshooarora** [comment]
Thanks Vimal.  We can keep this approach, but it will be good to point out in the docs about the side-affects.

**Comment by anshooarora** [comment]
This feature will be available with ExtentReports v3, the following commits enable:

https://github.com/anshooarora/extentreports-java/commit/48c0ca525b266b32edbb30e55b4f88b8aa7d0c78
f21c7060700f2c1ca2c0250ec0b7dc54f4704d63
