### ISSUE TITLE
ExtentX report shows blank chart

### ISSUE THREAD

**Issue by rudrahotta** [anshooarora/extentx#90]
Hi,
we are trying for extentX for our automation test result and  local reports are looks fine, but on extentx nodejs app, the report doesn't show no data for any chart on the dash board (have attached the screen short). not sure what is the root cause. can you please help on this?

![image](https://cloud.githubusercontent.com/assets/20122864/20553457/b3c0eb5c-b109-11e6-9661-40be7641272e.png)

**Comment by anshooarora** [comment]
ExtentReports - Java or .NET?  Versions?

**Comment by rudrahotta** [comment]
It is .Net version 2.41 stable one.

**Comment by rudrahotta** [comment]
My bad, I was using extentx-0.2.2-alpha version. Closing the ticket.
