### ISSUE TITLE
ExtentX not showing the charts on the dashboard.

### ISSUE THREAD

**Issue by qadatascience** [anshooarora/extentx#92]
Hello Anshoo,

We are really excited to see the concept of ExtentX report server and the kind of test analysis we can do with it.

We have implemented Extent Report v3.0.1 for the reports.
For report server, we have implemented Extentx-0.2.2-alpha as per the given guidelines.

The reports are getting generated properly with superb charts.
However, we are **unable to see the charts on the extentx** report server.
All the other functionality except charts is working as expected on the extentx.

Kindly look into it asap as we have delivery ahead.
Please find the screenshot for the extentx report server attached herewith.

![extentx charts not displayed](https://cloud.githubusercontent.com/assets/24431528/20964231/a62632f2-bc96-11e6-8732-987543d54800.png)

Thanks and Regards,
QA Data Science

**Comment by anshooarora** [comment]
I would recommend upgrading to 3.0.2 and ExtentX 1.0.0, a lot of bug fixes available.  This particular issue was also due to mismatched versions but ExtentX officially supports ExtentReports 3.0.1+.
