### ISSUE TITLE
Trend report distorts when test execution is terminated prematurely.

### ISSUE THREAD

**Issue by prasanta-biswas** [anshooarora/extentx#93]
The extentx report dashboard distorts when test execution is terminated prematurely. It adds two more columns i.e. Grand Child and Grand Child Distribution.

<img width="1191" alt="screen shot 2016-12-07 at 7 14 51 pm" src="https://cloud.githubusercontent.com/assets/22316119/20970011/8b76a066-bcb1-11e6-8893-b3f56d257d06.png">

<img width="1211" alt="screen shot 2016-12-07 at 7 15 31 pm" src="https://cloud.githubusercontent.com/assets/22316119/20970017/942e7bb6-bcb1-11e6-9fac-5d0c1a6d5107.png">

**Comment by anshooarora** [comment]
fyi -  This issue is fixed as of version 1.0.0.
