### ISSUE TITLE
Blank reports being generated in latest clone of repository

### ISSUE THREAD

**Issue by ujjwalmadeye** [anshooarora/extentx#94]
I took the latest clone of the extentx repository and installed , after the test runs the reports are blank in extentx. Should I uninstall and install released version ? what are the steps for uninstalling ?

**Comment by anshooarora** [comment]
Which version, Java or .NET?

If Java, I would recommend upgrading to 3.0.2 and ExtentX 1.0.0, a lot of bug fixes available.

If .NET, an upgrade is in the works and will be released in a few weeks, with complete ExtentX 1.0 support.
