### ISSUE TITLE
Getting issue when test fails and screenshot upload in extenx

### ISSUE THREAD

**Issue by dkjha52** [anshooarora/extentx#99]
I am getting below issue - 
java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 127.0.0.1:27017/csrfToken

Using - ExtentX 0.2.2-alpha with extentreports-3.0.0

**Comment by anshooarora** [comment]
To resolve this,  please upgrade to extentreports-3.0.2 and ExtentX 1.0.0.
